// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pgSfCFo9UF4777TfUQAq8w
// Component: 5zx6v9Q6yd6h
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  useCurrentUser
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import Step1Button from "../../Step1Button"; // plasmic-import: HRPieMAss-cJ/component
import "@plasmicapp/react-web/lib/plasmic.css";
import sty from "./PlasmicStep2Button.module.css"; // plasmic-import: 5zx6v9Q6yd6h/css

createPlasmicElementProxy;

export const PlasmicStep2Button__VariantProps = new Array();

export const PlasmicStep2Button__ArgProps = new Array();

const $$ = {};

function PlasmicStep2Button__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  return (
    <Step1Button
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames("__wab_instance", sty.root)}
    />
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicStep2Button__ArgProps,
          internalVariantPropNames: PlasmicStep2Button__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicStep2Button__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicStep2Button";
  } else {
    func.displayName = `PlasmicStep2Button.${nodeName}`;
  }
  return func;
}

export const PlasmicStep2Button = Object.assign(
  // Top-level PlasmicStep2Button renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicStep2Button
    internalVariantProps: PlasmicStep2Button__VariantProps,
    internalArgProps: PlasmicStep2Button__ArgProps
  }
);

export default PlasmicStep2Button;
/* prettier-ignore-end */
