// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pgSfCFo9UF4777TfUQAq8w
// Component: CIOMU0qtKeTz
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  useCurrentUser
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import Energy from "../../Energy"; // plasmic-import: x1Cyf2ueyA9p/component
import Diamond from "../../Diamond"; // plasmic-import: 3lAn5o1Jo_ek/component
import Day from "../../Day"; // plasmic-import: 6pws9FrBaH0B/component
import EnergyNumber from "../../EnergyNumber"; // plasmic-import: 5_Y0di5blnq0/component
import DiamondNumber from "../../DiamondNumber"; // plasmic-import: 401Fmr7Nu67-/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: pgSfCFo9UF4777TfUQAq8w/projectcss
import sty from "./PlasmicDataBox.module.css"; // plasmic-import: CIOMU0qtKeTz/css

createPlasmicElementProxy;

export const PlasmicDataBox__VariantProps = new Array();

export const PlasmicDataBox__ArgProps = new Array();

const $$ = {};

function PlasmicDataBox__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <Energy
        data-plasmic-name={"energy"}
        data-plasmic-override={overrides.energy}
        className={classNames("__wab_instance", sty.energy)}
      />

      <Diamond
        data-plasmic-name={"diamond"}
        data-plasmic-override={overrides.diamond}
        className={classNames("__wab_instance", sty.diamond)}
      />

      <Day
        data-plasmic-name={"day"}
        data-plasmic-override={overrides.day}
        className={classNames("__wab_instance", sty.day)}
      />

      <EnergyNumber
        data-plasmic-name={"energyNumber"}
        data-plasmic-override={overrides.energyNumber}
        className={classNames("__wab_instance", sty.energyNumber)}
      />

      <DiamondNumber
        className={classNames("__wab_instance", sty.diamondNumber__to72M)}
      />

      <DiamondNumber
        className={classNames("__wab_instance", sty.diamondNumber__sNtQi)}
      />
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "energy", "diamond", "day", "energyNumber"],
  energy: ["energy"],
  diamond: ["diamond"],
  day: ["day"],
  energyNumber: ["energyNumber"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicDataBox__ArgProps,
          internalVariantPropNames: PlasmicDataBox__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicDataBox__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDataBox";
  } else {
    func.displayName = `PlasmicDataBox.${nodeName}`;
  }
  return func;
}

export const PlasmicDataBox = Object.assign(
  // Top-level PlasmicDataBox renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    energy: makeNodeComponent("energy"),
    diamond: makeNodeComponent("diamond"),
    day: makeNodeComponent("day"),
    energyNumber: makeNodeComponent("energyNumber"),
    // Metadata about props expected for PlasmicDataBox
    internalVariantProps: PlasmicDataBox__VariantProps,
    internalArgProps: PlasmicDataBox__ArgProps
  }
);

export default PlasmicDataBox;
/* prettier-ignore-end */
