// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pgSfCFo9UF4777TfUQAq8w
// Component: rT-mkRW9chFm
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  useCurrentUser
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import StepNumber from "../../StepNumber"; // plasmic-import: f09tyOZ4zvnw/component
import "@plasmicapp/react-web/lib/plasmic.css";
import sty from "./PlasmicStepNumber2.module.css"; // plasmic-import: rT-mkRW9chFm/css

createPlasmicElementProxy;

export const PlasmicStepNumber2__VariantProps = new Array();

export const PlasmicStepNumber2__ArgProps = new Array();

const $$ = {};

function PlasmicStepNumber2__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  return (
    <StepNumber
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames("__wab_instance", sty.root)}
    />
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicStepNumber2__ArgProps,
          internalVariantPropNames: PlasmicStepNumber2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicStepNumber2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicStepNumber2";
  } else {
    func.displayName = `PlasmicStepNumber2.${nodeName}`;
  }
  return func;
}

export const PlasmicStepNumber2 = Object.assign(
  // Top-level PlasmicStepNumber2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicStepNumber2
    internalVariantProps: PlasmicStepNumber2__VariantProps,
    internalArgProps: PlasmicStepNumber2__ArgProps
  }
);

export default PlasmicStepNumber2;
/* prettier-ignore-end */
