// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pgSfCFo9UF4777TfUQAq8w
// Component: ORuN3NQ0-wQo
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  useCurrentUser
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import LevelText from "../../LevelText"; // plasmic-import: DMENlZyEeyAA/component
import Level2 from "../../Level2"; // plasmic-import: YU8Vlb5Q6Jlt/component
import Unit1Title from "../../Unit1Title"; // plasmic-import: fhmxFVFG9WOd/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: pgSfCFo9UF4777TfUQAq8w/projectcss
import sty from "./PlasmicSecondNavbar.module.css"; // plasmic-import: ORuN3NQ0-wQo/css

createPlasmicElementProxy;

export const PlasmicSecondNavbar__VariantProps = new Array();

export const PlasmicSecondNavbar__ArgProps = new Array();

const $$ = {};

function PlasmicSecondNavbar__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  return (
    <section
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <LevelText
        data-plasmic-name={"levelText"}
        data-plasmic-override={overrides.levelText}
        className={classNames("__wab_instance", sty.levelText)}
      />

      <Level2
        data-plasmic-name={"level2"}
        data-plasmic-override={overrides.level2}
        className={classNames("__wab_instance", sty.level2)}
      />

      <Unit1Title
        data-plasmic-name={"unit1Title"}
        data-plasmic-override={overrides.unit1Title}
        className={classNames("__wab_instance", sty.unit1Title)}
      />
    </section>
  );
}

const PlasmicDescendants = {
  root: ["root", "levelText", "level2", "unit1Title"],
  levelText: ["levelText"],
  level2: ["level2"],
  unit1Title: ["unit1Title"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSecondNavbar__ArgProps,
          internalVariantPropNames: PlasmicSecondNavbar__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSecondNavbar__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSecondNavbar";
  } else {
    func.displayName = `PlasmicSecondNavbar.${nodeName}`;
  }
  return func;
}

export const PlasmicSecondNavbar = Object.assign(
  // Top-level PlasmicSecondNavbar renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    levelText: makeNodeComponent("levelText"),
    level2: makeNodeComponent("level2"),
    unit1Title: makeNodeComponent("unit1Title"),
    // Metadata about props expected for PlasmicSecondNavbar
    internalVariantProps: PlasmicSecondNavbar__VariantProps,
    internalArgProps: PlasmicSecondNavbar__ArgProps
  }
);

export default PlasmicSecondNavbar;
/* prettier-ignore-end */
