// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pgSfCFo9UF4777TfUQAq8w
// Component: x1Cyf2ueyA9p
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  useCurrentUser
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: pgSfCFo9UF4777TfUQAq8w/projectcss
import sty from "./PlasmicEnergy.module.css"; // plasmic-import: x1Cyf2ueyA9p/css
import energywebpLNpiThjYziK from "./images/energywebp.webp"; // plasmic-import: lNpiThjYziK-/picture

createPlasmicElementProxy;

export const PlasmicEnergy__VariantProps = new Array();

export const PlasmicEnergy__ArgProps = new Array();

const $$ = {};

function PlasmicEnergy__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  return (
    <PlasmicImg__
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      alt={""}
      className={classNames(
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
      displayHeight={"19px"}
      displayMaxHeight={"none"}
      displayMaxWidth={"100%"}
      displayMinHeight={"0"}
      displayMinWidth={"0"}
      displayWidth={"6.28%"}
      loading={"lazy"}
      src={{
        src: energywebpLNpiThjYziK,
        fullWidth: 1920,
        fullHeight: 1920,
        aspectRatio: undefined
      }}
    />
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicEnergy__ArgProps,
          internalVariantPropNames: PlasmicEnergy__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicEnergy__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicEnergy";
  } else {
    func.displayName = `PlasmicEnergy.${nodeName}`;
  }
  return func;
}

export const PlasmicEnergy = Object.assign(
  // Top-level PlasmicEnergy renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicEnergy
    internalVariantProps: PlasmicEnergy__VariantProps,
    internalArgProps: PlasmicEnergy__ArgProps
  }
);

export default PlasmicEnergy;
/* prettier-ignore-end */
