// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pgSfCFo9UF4777TfUQAq8w
// Component: DMENlZyEeyAA
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  useCurrentUser
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import Level from "../../Level"; // plasmic-import: jH-XFI3TxSP7/component
import "@plasmicapp/react-web/lib/plasmic.css";
import sty from "./PlasmicLevelText.module.css"; // plasmic-import: DMENlZyEeyAA/css

createPlasmicElementProxy;

export const PlasmicLevelText__VariantProps = new Array();

export const PlasmicLevelText__ArgProps = new Array();

const $$ = {};

function PlasmicLevelText__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  return (
    <Level
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames("__wab_instance", sty.root)}
    />
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLevelText__ArgProps,
          internalVariantPropNames: PlasmicLevelText__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLevelText__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLevelText";
  } else {
    func.displayName = `PlasmicLevelText.${nodeName}`;
  }
  return func;
}

export const PlasmicLevelText = Object.assign(
  // Top-level PlasmicLevelText renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicLevelText
    internalVariantProps: PlasmicLevelText__VariantProps,
    internalArgProps: PlasmicLevelText__ArgProps
  }
);

export default PlasmicLevelText;
/* prettier-ignore-end */
