// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pgSfCFo9UF4777TfUQAq8w
// Component: O2o41IPAOcPP
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  useCurrentUser
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import ProfileText from "../../ProfileText"; // plasmic-import: z-c-7BMo6bBI/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: pgSfCFo9UF4777TfUQAq8w/projectcss
import sty from "./PlasmicProfileButtom.module.css"; // plasmic-import: O2o41IPAOcPP/css

createPlasmicElementProxy;

export const PlasmicProfileButtom__VariantProps = new Array();

export const PlasmicProfileButtom__ArgProps = new Array();

const $$ = {};

function PlasmicProfileButtom__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  return (
    <button
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.button,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <ProfileText
        data-plasmic-name={"profileText"}
        data-plasmic-override={overrides.profileText}
        className={classNames("__wab_instance", sty.profileText)}
      />
    </button>
  );
}

const PlasmicDescendants = {
  root: ["root", "profileText"],
  profileText: ["profileText"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicProfileButtom__ArgProps,
          internalVariantPropNames: PlasmicProfileButtom__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicProfileButtom__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProfileButtom";
  } else {
    func.displayName = `PlasmicProfileButtom.${nodeName}`;
  }
  return func;
}

export const PlasmicProfileButtom = Object.assign(
  // Top-level PlasmicProfileButtom renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    profileText: makeNodeComponent("profileText"),
    // Metadata about props expected for PlasmicProfileButtom
    internalVariantProps: PlasmicProfileButtom__VariantProps,
    internalArgProps: PlasmicProfileButtom__ArgProps
  }
);

export default PlasmicProfileButtom;
/* prettier-ignore-end */
