// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pgSfCFo9UF4777TfUQAq8w
// Component: ATsYm0k3JcVt
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  useCurrentUser
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import MainNavbar from "../../MainNavbar"; // plasmic-import: Y06WnZm__AX_/component
import SecondNavbar from "../../SecondNavbar"; // plasmic-import: ORuN3NQ0-wQo/component
import HomeIcon from "../../HomeIcon"; // plasmic-import: 7M8pczqlI6FJ/component
import ProfileIcon from "../../ProfileIcon"; // plasmic-import: 1g1hBhQX_CnB/component
import PlayIcon from "../../PlayIcon"; // plasmic-import: kPQlxzG25Uar/component
import Step1Button from "../../Step1Button"; // plasmic-import: HRPieMAss-cJ/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: pgSfCFo9UF4777TfUQAq8w/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: ATsYm0k3JcVt/css
import arrowIconpngLMKrAf8DR8Jx from "./images/arrowIconpng.png"; // plasmic-import: lMKrAF8dR8JX/picture
import starIconpngKbuqFtIug6B from "./images/starIconpng.png"; // plasmic-import: KbuqFt-Iug6B/picture

createPlasmicElementProxy;

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const $$ = {};

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <MainNavbar
            data-plasmic-name={"mainNavbar"}
            data-plasmic-override={overrides.mainNavbar}
            className={classNames("__wab_instance", sty.mainNavbar)}
          />

          <SecondNavbar
            data-plasmic-name={"secondNavbar"}
            data-plasmic-override={overrides.secondNavbar}
            className={classNames("__wab_instance", sty.secondNavbar)}
          />

          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__ghI0W)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"55px"}
            loading={"lazy"}
            src={{
              src: arrowIconpngLMKrAf8DR8Jx,
              fullWidth: 512,
              fullHeight: 512,
              aspectRatio: undefined
            }}
          />

          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__lIiXe)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"55px"}
            loading={"lazy"}
            src={{
              src: arrowIconpngLMKrAf8DR8Jx,
              fullWidth: 512,
              fullHeight: 512,
              aspectRatio: undefined
            }}
          />

          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__n5Hel)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"55px"}
            loading={"lazy"}
            src={{
              src: arrowIconpngLMKrAf8DR8Jx,
              fullWidth: 512,
              fullHeight: 512,
              aspectRatio: undefined
            }}
          />

          <PlasmicImg__
            alt={""}
            className={classNames(sty.img___4Ua8G)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"55px"}
            loading={"lazy"}
            src={{
              src: arrowIconpngLMKrAf8DR8Jx,
              fullWidth: 512,
              fullHeight: 512,
              aspectRatio: undefined
            }}
          />

          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__nWIff)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"30px"}
            loading={"lazy"}
            src={{
              src: starIconpngKbuqFtIug6B,
              fullWidth: 256,
              fullHeight: 256,
              aspectRatio: undefined
            }}
          />

          <PlasmicImg__
            alt={""}
            className={classNames(sty.img___7DdWo)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"30px"}
            loading={"lazy"}
            src={{
              src: starIconpngKbuqFtIug6B,
              fullWidth: 256,
              fullHeight: 256,
              aspectRatio: undefined
            }}
          />

          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__enAel)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"30px"}
            loading={"lazy"}
            src={{
              src: starIconpngKbuqFtIug6B,
              fullWidth: 256,
              fullHeight: 256,
              aspectRatio: undefined
            }}
          />

          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__qrKjq)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"30px"}
            loading={"lazy"}
            src={{
              src: starIconpngKbuqFtIug6B,
              fullWidth: 256,
              fullHeight: 256,
              aspectRatio: undefined
            }}
          />

          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__g4VyF)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"30px"}
            loading={"lazy"}
            src={{
              src: starIconpngKbuqFtIug6B,
              fullWidth: 256,
              fullHeight: 256,
              aspectRatio: undefined
            }}
          />

          <div
            data-plasmic-name={"freeBox"}
            data-plasmic-override={overrides.freeBox}
            className={classNames(projectcss.all, sty.freeBox)}
          >
            <HomeIcon
              data-plasmic-name={"homeIcon"}
              data-plasmic-override={overrides.homeIcon}
              className={classNames("__wab_instance", sty.homeIcon)}
            />

            <ProfileIcon
              data-plasmic-name={"profileIcon"}
              data-plasmic-override={overrides.profileIcon}
              className={classNames("__wab_instance", sty.profileIcon)}
            />

            <PlayIcon
              data-plasmic-name={"playIcon"}
              data-plasmic-override={overrides.playIcon}
              className={classNames("__wab_instance", sty.playIcon)}
            />
          </div>
          <Step1Button
            className={classNames("__wab_instance", sty.step1Button__y7Jj)}
          />

          <Step1Button
            className={classNames("__wab_instance", sty.step1Button__dkSpc)}
          />

          <Step1Button
            className={classNames("__wab_instance", sty.step1Button___1Gfzd)}
          />

          <Step1Button
            className={classNames("__wab_instance", sty.step1Button__ppCd)}
          />

          <Step1Button
            className={classNames("__wab_instance", sty.step1Button__zVc21)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "mainNavbar",
    "secondNavbar",
    "freeBox",
    "homeIcon",
    "profileIcon",
    "playIcon"
  ],

  mainNavbar: ["mainNavbar"],
  secondNavbar: ["secondNavbar"],
  freeBox: ["freeBox", "homeIcon", "profileIcon", "playIcon"],
  homeIcon: ["homeIcon"],
  profileIcon: ["profileIcon"],
  playIcon: ["playIcon"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    mainNavbar: makeNodeComponent("mainNavbar"),
    secondNavbar: makeNodeComponent("secondNavbar"),
    freeBox: makeNodeComponent("freeBox"),
    homeIcon: makeNodeComponent("homeIcon"),
    profileIcon: makeNodeComponent("profileIcon"),
    playIcon: makeNodeComponent("playIcon"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
