// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pgSfCFo9UF4777TfUQAq8w
// Component: 3lAn5o1Jo_ek
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  useCurrentUser
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: pgSfCFo9UF4777TfUQAq8w/projectcss
import sty from "./PlasmicDiamond.module.css"; // plasmic-import: 3lAn5o1Jo_ek/css
import diamondpngHIaVk62HQ1Mx from "./images/diamondpng.png"; // plasmic-import: hIaVK62hQ1MX/picture

createPlasmicElementProxy;

export const PlasmicDiamond__VariantProps = new Array();

export const PlasmicDiamond__ArgProps = new Array();

const $$ = {};

function PlasmicDiamond__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  return (
    <PlasmicImg__
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      alt={""}
      className={classNames(
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
      displayHeight={"auto"}
      displayMaxHeight={"none"}
      displayMaxWidth={"100%"}
      displayMinHeight={"0"}
      displayMinWidth={"0"}
      displayWidth={"8%"}
      loading={"lazy"}
      src={{
        src: diamondpngHIaVk62HQ1Mx,
        fullWidth: 315,
        fullHeight: 231,
        aspectRatio: undefined
      }}
    />
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicDiamond__ArgProps,
          internalVariantPropNames: PlasmicDiamond__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicDiamond__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDiamond";
  } else {
    func.displayName = `PlasmicDiamond.${nodeName}`;
  }
  return func;
}

export const PlasmicDiamond = Object.assign(
  // Top-level PlasmicDiamond renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicDiamond
    internalVariantProps: PlasmicDiamond__VariantProps,
    internalArgProps: PlasmicDiamond__ArgProps
  }
);

export default PlasmicDiamond;
/* prettier-ignore-end */
